# Generated by Django 5.2.8 on 2025-11-07 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('phone_last4', models.CharField(max_length=4, verbose_name='연락처 뒷자리')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성')], max_length=10)),
                ('education', models.CharField(blank=True, max_length=50)),
                ('vision', models.CharField(choices=[('normal', '정상'), ('corrected', '교정')], max_length=20, verbose_name='시력')),
                ('has_aac_experience', models.BooleanField(default=False)),
                ('has_aac_education', models.BooleanField(default=False)),
                ('consent_agreed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('block_order', models.IntegerField(choices=[(1, 'AI first'), (2, 'Existing first')])),
            ],
            options={
                'db_table': 'participants',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easier_to_understand', models.CharField(choices=[('ai', 'AI 생성 상징'), ('kaac', 'KAAC 상징'), ('similar', '비슷함')], max_length=10)),
                ('preference', models.CharField(choices=[('ai', 'AI 생성 상징'), ('kaac', 'KAAC 상징'), ('similar', '비슷함')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='api.participant')),
            ],
            options={
                'db_table': 'preferences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrialResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_number', models.IntegerField()),
                ('is_practice', models.BooleanField(default=False)),
                ('target_word', models.CharField(max_length=20)),
                ('symbol_type', models.CharField(choices=[('ai', 'AI 생성'), ('kaac', 'KAAC')], max_length=10)),
                ('block_type', models.CharField(max_length=10)),
                ('presented_symbols', models.JSONField()),
                ('selected_symbol', models.CharField(max_length=50)),
                ('is_correct', models.BooleanField()),
                ('reaction_time', models.IntegerField()),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.participant')),
            ],
            options={
                'db_table': 'trial_responses',
                'ordering': ['participant', 'trial_number'],
                'indexes': [models.Index(fields=['participant', 'trial_number'], name='trial_respo_partici_c32191_idx'), models.Index(fields=['symbol_type'], name='trial_respo_symbol__acf180_idx')],
            },
        ),
    ]
