# Generated by Django 5.2.8 on 2025-11-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialresponse',
            name='error_count',
            field=models.IntegerField(default=0),
        ),
    ]
