# Generated by Django 5.2.8 on 2025-11-09 05:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trialresponse_error_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_word', models.CharField(max_length=20, verbose_name='대상 단어')),
                ('ai_position', models.CharField(choices=[('left', '왼쪽'), ('right', '오른쪽')], max_length=10, verbose_name='AI 위치')),
                ('chosen', models.CharField(choices=[('left', '왼쪽'), ('right', '오른쪽'), ('similar', '비슷하다')], max_length=10, verbose_name='선택')),
                ('chosen_type', models.CharField(choices=[('ai', 'AI 상징'), ('kaac', 'KAAC 상징'), ('similar', '비슷하다')], max_length=10, verbose_name='선택 유형')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol_preferences', to='api.participant')),
            ],
            options={
                'db_table': 'symbol_preferences',
                'ordering': ['participant', 'target_word'],
                'indexes': [models.Index(fields=['participant', 'target_word'], name='symbol_pref_partici_1e63f4_idx'), models.Index(fields=['chosen_type'], name='symbol_pref_chosen__23a4f3_idx')],
                'unique_together': {('participant', 'target_word')},
            },
        ),
    ]
