# Generated by Django 5.2.8 on 2025-11-09 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_symbolpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
